In [1]:
## import library
import pandas as pd

In [2]:
## import census data and get sample of 15
dfcensus = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/conditional-conversion/NYC_Census_2020_2010_geotype.csv")
dfcensus.head()

,Year,GeoType,Borough,Community District Number,Community District Name,Total Population,Average household size,Children,Latino,White non-Hispanic,Black non-Hispanic,Asian,Other race,Two or more races,Total housing units,Occupied housing units,Vacant housing units
0,2020,CD,Queens,407,Queens Community District 7,"269,587",2.75,"45,543","48,845","55,882","5,412","154,404","1,575","3,469","102,836","97,059","5,777"
1,2020,CD,Brooklyn,311,Brooklyn Community District 11,"198,870",2.94,"42,380","31,489","72,496","2,353","86,067","1,081","5,384","71,074","67,236","3,838"
2,2020,CD,Queens,404,Queens Community District 4,"181,025",3.24,"38,213","93,972","9,329","7,679","65,963","1,692","2,390","57,748","55,202","2,546"
3,2020,CD,Queens,408,Queens Community District 8,"161,402",2.76,"32,754","29,486","44,302","18,682","60,413","3,200","5,319","59,385","56,623","2,762"
4,2020,CD,Queens,411,Queens Community District 11,"122,211",2.69,"21,612","14,460","41,967","2,641","59,980",779,"2,384","47,357","45,204","2,153"

In [3]:
# get info
dfcensus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       59 non-null     int64
 1   GeoType                    59 non-null     object
 2   Borough                    59 non-null     object
 3   Community District Number  59 non-null     int64
 4   Community District Name    59 non-null     object
 5   Total Population           59 non-null     object
 6   Average household size     59 non-null     float64
 7   Children                   59 non-null     object
 8   Latino                     59 non-null     object
 9   White non-Hispanic         59 non-null     object
 10  Black non-Hispanic         59 non-null     object
 11  Asian                      59 non-null     object
 12  Other race                 59 non-null     object
 13  Two or more races          59 non-null     object
 14  Total housing units        59 non-null     object
 15  Occupied housing units     59 non-null     object
 16  Vacant housing units       59 non-null     object
dtypes: float64(1), int64(2), object(14)
memory usage: 8.0+ KB

In [4]:
## import SNAP benefits and see sample of 15
dfsnap = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/conditional-conversion/SNAP_benefits_borough.csv")

In [5]:
## get info
dfsnap.sample(10)

,Month,Boro,Community District,BC_SNAP_Recipients,BC_SNAP_Households
134,3/1/21,Brooklyn,K05,66213,38486
994,9/1/22,Queens,Q09,24956,14508
264,9/1/21,Brooklyn,K05,65996,38331
32,9/1/20,Brooklyn,K09,22023,13644
218,6/1/21,Brooklyn,K18,31491,19360
357,3/1/22,Manhattan,M04,13219,10119
969,9/1/22,Brooklyn,K02,14125,9689
941,6/1/22,Staten Island,S01,39760,21283
2,9/1/20,Manhattan,M03,37879,26041
599,3/1/19,BROOKLYN,K01,50622,19950

In [6]:
# we have to merge the two data sets, but our data is written in different ways?

In [7]:
## import homeless shelter data and get sample of 15
dfshelter = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/conditional-conversion/HomelessShelterbyBorough.csv")
dfshelter

,Report Date,Borough,Community District,Census Type,Adult Family Commercial Hotel,Adult Family Shelter,Adult Shelter,Adult Shelter Commercial Hotel,Family Cluster,Family with Children Commercial Hotel,Family with Children Shelter
0,10/31/20,Bronx,1,Individuals,NaN,189.0,73.0,140.0,31.0,64.0,1202.0
1,10/31/20,Bronx,2,Individuals,NaN,160.0,0.0,NaN,204.0,NaN,866.0
2,10/31/20,Bronx,3,Individuals,NaN,258.0,218.0,123.0,62.0,115.0,1295.0
3,10/31/20,Bronx,4,Individuals,NaN,NaN,206.0,99.0,910.0,NaN,2134.0
4,10/31/20,Bronx,5,Individuals,NaN,203.0,0.0,NaN,755.0,NaN,1054.0
...,...,...,...,...,...,...,...,...,...,...,...
3181,3/31/23,Queens,13,Individuals,NaN,NaN,131.0,895.0,NaN,NaN,832.0
3182,3/31/23,Queens,14,Individuals,NaN,321.0,102.0,339.0,NaN,NaN,180.0
3183,3/31/23,Staten Island,1,Individuals,NaN,NaN,NaN,NaN,NaN,NaN,135.0
3184,3/31/23,Staten Island,2,Individuals,NaN,NaN,NaN,NaN,NaN,546.0,NaN
3185,3/31/23,Staten Island,3,Individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
## get info
dfshelter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3186 entries, 0 to 3185
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Report Date                            3186 non-null   object
 1   Borough                                3186 non-null   object
 2   Community District                     3186 non-null   int64
 3   Census Type                            3186 non-null   object
 4   Adult Family Commercial Hotel          80 non-null     float64
 5   Adult Family Shelter                   802 non-null    float64
 6   Adult Shelter                          1797 non-null   float64
 7   Adult Shelter Commercial Hotel         1242 non-null   float64
 8   Family Cluster                         402 non-null    float64
 9   Family with Children Commercial Hotel  886 non-null    float64
 10  Family with Children Shelter           2168 non-null   float64
dtypes: float64(7), int64(1), object(3)
memory usage: 273.9+ KB

In [9]:
# what we're noticing is that everything is written differently (staten, 1 vs M1 vs Staten 01)

In [10]:
# this is going to be for homework: using lambda, you're going to be creating new columns to join together the information and get all the same community districts

In [11]:
dfcensus.head(5)

,Year,GeoType,Borough,Community District Number,Community District Name,Total Population,Average household size,Children,Latino,White non-Hispanic,Black non-Hispanic,Asian,Other race,Two or more races,Total housing units,Occupied housing units,Vacant housing units
0,2020,CD,Queens,407,Queens Community District 7,"269,587",2.75,"45,543","48,845","55,882","5,412","154,404","1,575","3,469","102,836","97,059","5,777"
1,2020,CD,Brooklyn,311,Brooklyn Community District 11,"198,870",2.94,"42,380","31,489","72,496","2,353","86,067","1,081","5,384","71,074","67,236","3,838"
2,2020,CD,Queens,404,Queens Community District 4,"181,025",3.24,"38,213","93,972","9,329","7,679","65,963","1,692","2,390","57,748","55,202","2,546"
3,2020,CD,Queens,408,Queens Community District 8,"161,402",2.76,"32,754","29,486","44,302","18,682","60,413","3,200","5,319","59,385","56,623","2,762"
4,2020,CD,Queens,411,Queens Community District 11,"122,211",2.69,"21,612","14,460","41,967","2,641","59,980",779,"2,384","47,357","45,204","2,153"

In [12]:
#Homework

In [13]:
## recall dfshelter
dfshelter.sample(10)

,Report Date,Borough,Community District,Census Type,Adult Family Commercial Hotel,Adult Family Shelter,Adult Shelter,Adult Shelter Commercial Hotel,Family Cluster,Family with Children Commercial Hotel,Family with Children Shelter
613,7/31/21,Queens,14,Individuals,NaN,270.0,50.0,93.0,NaN,70.0,125.0
1910,8/31/19,Brooklyn,10,Individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2416,4/30/20,Queens,14,Individuals,NaN,306.0,84.0,NaN,NaN,171.0,143.0
2903,11/30/22,Brooklyn,1,Individuals,NaN,165.0,1061.0,48.0,NaN,233.0,NaN
3060,1/31/23,Queens,10,Individuals,NaN,NaN,173.0,82.0,NaN,346.0,NaN
1403,8/31/18,Queens,5,Individuals,NaN,NaN,NaN,103.0,NaN,NaN,NaN
2910,11/30/22,Brooklyn,8,Individuals,NaN,NaN,371.0,88.0,NaN,NaN,498.0
2427,5/31/20,Bronx,8,Individuals,NaN,NaN,NaN,NaN,NaN,NaN,235.0
2006,9/30/19,Staten Island,3,Individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2421,5/31/20,Bronx,2,Individuals,NaN,162.0,NaN,NaN,218.0,NaN,769.0

In [14]:
# going to have to give the function two arguments 
def convertShelter(cd, borough):
    if cd < 10: 
        str_cd = str(cd)
        str_cd = "0" + str_cd

    else: 
        str_cd = str(cd)

    if borough == "Manhattan":
        str_cd_code = f"M{str_cd}"
    elif borough == "Brooklyn":
        str_cd_code = f"K{str_cd}"
    elif borough == "Bronx":
        str_cd_code = f"B{str_cd}"
    elif borough == "Staten Island":
        str_cd_code = f"S{str_cd}"
    elif borough == "Queens":
        str_cd_code = f"Q{str_cd}"
    else: str_cd_code = "FLAG"
    return str_cd_code

# it has to be indnted, so it knows to read the sentence above it 


# if borough = manhattan, make it X 
# turn community district into a two digit number

In [15]:
## test it

test = convertShelter(8, "Brooklyn")
print(test)

K08

In [16]:
# yay it works!

In [17]:
# these were my other trials for shelter data 
#dfshelter["updated_cd_shelter"] = dfshelter.apply(lambda x: convertShelter(dfshelter["Community District"],dfshelter["Borough"]), axis = 1)

#(convertShelter(dfshelter["Community District"],dfshelter["Borough"]), axis = 1)
#

In [18]:
## use on shelter data 
# I had to use chat gpt to help me get here 
# axis = 1 included because you're applying this function across the rows 

dfshelter["updated_cd_shelter"] = dfshelter.apply(
    lambda x: convertShelter(x["Community District"], x["Borough"]), axis=1
)

dfshelter

,Report Date,Borough,Community District,Census Type,Adult Family Commercial Hotel,Adult Family Shelter,Adult Shelter,Adult Shelter Commercial Hotel,Family Cluster,Family with Children Commercial Hotel,Family with Children Shelter,updated_cd_shelter
0,10/31/20,Bronx,1,Individuals,NaN,189.0,73.0,140.0,31.0,64.0,1202.0,B01
1,10/31/20,Bronx,2,Individuals,NaN,160.0,0.0,NaN,204.0,NaN,866.0,B02
2,10/31/20,Bronx,3,Individuals,NaN,258.0,218.0,123.0,62.0,115.0,1295.0,B03
3,10/31/20,Bronx,4,Individuals,NaN,NaN,206.0,99.0,910.0,NaN,2134.0,B04
4,10/31/20,Bronx,5,Individuals,NaN,203.0,0.0,NaN,755.0,NaN,1054.0,B05
...,...,...,...,...,...,...,...,...,...,...,...,...
3181,3/31/23,Queens,13,Individuals,NaN,NaN,131.0,895.0,NaN,NaN,832.0,Q13
3182,3/31/23,Queens,14,Individuals,NaN,321.0,102.0,339.0,NaN,NaN,180.0,Q14
3183,3/31/23,Staten Island,1,Individuals,NaN,NaN,NaN,NaN,NaN,NaN,135.0,S01
3184,3/31/23,Staten Island,2,Individuals,NaN,NaN,NaN,NaN,NaN,546.0,NaN,S02
3185,3/31/23,Staten Island,3,Individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S03

In [19]:
# reorder columns

In [20]:
## call columns into list
list(dfshelter.columns)

['Report Date',
 'Borough',
 'Community District',
 'Census Type',
 'Adult Family Commercial Hotel',
 'Adult Family Shelter',
 'Adult Shelter',
 'Adult Shelter Commercial Hotel',
 'Family Cluster',
 'Family with Children Commercial Hotel',
 'Family with Children Shelter',
 'updated_cd_shelter']

In [21]:
## redorder and call
dfshelter = dfshelter[['Report Date',
 'Borough',
 'Community District',
 'Census Type',
                       'updated_cd_shelter',
 'Adult Family Commercial Hotel',
 'Adult Family Shelter',
 'Adult Shelter',
 'Adult Shelter Commercial Hotel',
 'Family Cluster',
 'Family with Children Commercial Hotel',
 'Family with Children Shelter',
 ]]

In [22]:
dfshelter

,Report Date,Borough,Community District,Census Type,updated_cd_shelter,Adult Family Commercial Hotel,Adult Family Shelter,Adult Shelter,Adult Shelter Commercial Hotel,Family Cluster,Family with Children Commercial Hotel,Family with Children Shelter
0,10/31/20,Bronx,1,Individuals,B01,NaN,189.0,73.0,140.0,31.0,64.0,1202.0
1,10/31/20,Bronx,2,Individuals,B02,NaN,160.0,0.0,NaN,204.0,NaN,866.0
2,10/31/20,Bronx,3,Individuals,B03,NaN,258.0,218.0,123.0,62.0,115.0,1295.0
3,10/31/20,Bronx,4,Individuals,B04,NaN,NaN,206.0,99.0,910.0,NaN,2134.0
4,10/31/20,Bronx,5,Individuals,B05,NaN,203.0,0.0,NaN,755.0,NaN,1054.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3181,3/31/23,Queens,13,Individuals,Q13,NaN,NaN,131.0,895.0,NaN,NaN,832.0
3182,3/31/23,Queens,14,Individuals,Q14,NaN,321.0,102.0,339.0,NaN,NaN,180.0
3183,3/31/23,Staten Island,1,Individuals,S01,NaN,NaN,NaN,NaN,NaN,NaN,135.0
3184,3/31/23,Staten Island,2,Individuals,S02,NaN,NaN,NaN,NaN,NaN,546.0,NaN
3185,3/31/23,Staten Island,3,Individuals,S03,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
dfshelter.query("updated_cd_shelter == 'FLAG'")

Empty DataFrame
Columns: [Report Date, Borough, Community District, Census Type, updated_cd_shelter, Adult Family Commercial Hotel, Adult Family Shelter, Adult Shelter, Adult Shelter Commercial Hotel, Family Cluster, Family with Children Commercial Hotel, Family with Children Shelter]
Index: []

In [ ]:
# need a common column for things to merge on

In [30]:
dfcensus.head(2)

,Year,GeoType,Borough,Community District Number,Community District Name,Total Population,Average household size,Children,Latino,White non-Hispanic,Black non-Hispanic,Asian,Other race,Two or more races,Total housing units,Occupied housing units,Vacant housing units
0,2020,CD,Queens,407,Queens Community District 7,"269,587",2.75,"45,543","48,845","55,882","5,412","154,404","1,575","3,469","102,836","97,059","5,777"
1,2020,CD,Brooklyn,311,Brooklyn Community District 11,"198,870",2.94,"42,380","31,489","72,496","2,353","86,067","1,081","5,384","71,074","67,236","3,838"

In [ ]:
# notes from class on this homework 
# numbers don't actually have length, whereas objects are strings and do have length 
# unfortunately, I've lost the code for the updated cdn

In [34]:
# this would help you rename the column in the snap data frame 
dfsnap.rename(columns = {"Community District": "updated_cdn"}, inplace = True)